version: '3.3'
<<<<<<< HEAD
=======

>>>>>>> 5a32bb5457a90c5045e4b2f558b3cdc66e3a2b41
services:
  db:
    image: postgres
    environment:
     POSTGRES_DATABASE: docker
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: docker 
  moviedb:
    build:
      context: .
      dockerfile: Dockerfile
<<<<<<< HEAD
    command: gunicorn --bind 0.0.0.0:${PORT} wsgi
=======
>>>>>>> 5a32bb5457a90c5045e4b2f558b3cdc66e3a2b41
    env_file: ./.env
    volumes:
      - .:/app
    ports:
     - 3000:3000
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
<<<<<<< HEAD
      DB_HOST: ${db}
=======
      DB_HOST: db  
>>>>>>> 5a32bb5457a90c5045e4b2f558b3cdc66e3a2b41
      DATABASE: ${DATABASE}
    depends_on:
     - db